my_app/__init__.py
from flask import Flask
from my_app.product.views import product
from sqlalchemy import create_engine, text
import pymysql




app = Flask(__name__)

# Le pasamos la vista hello_word que hemos importado previamente. 
app.register_blueprint(product)






@app.template_filter('mayusculas')
def convertir_mayusculas(texto):
    return texto.upper()

@app.template_filter('mydouble')
def mydouble_filter(n:int):
    return n*2
    

my_app/product/views.py
from flask import Blueprint, render_template
from my_app.product.model.products import PRODUCTS

# Importa el diccionario: PRODUCTS del modulo product, model, products. 
# Contiene los datos para las pruebas de recuperacion y muestra de datos. 





# Recibe como parametro el nombre de la vista y el nombre del ejecutale (__name__). 
product = Blueprint('product', __name__)

@product.route('/')
@product.route('/home')
def index():
    # Abre la página index.html y le enviamos como parametro='products' 
    # el diccionario de PRODUCTOS.      
    return render_template('products/index.html', products=PRODUCTS)
    

@product.route('/product/<int:id>')
def show(id):
    product = PRODUCTS.get(id)    
    return render_template('products/show.html', product=product)

@product.route('/filter/<int:id>')
def filter(id):
    product = PRODUCTS.get(id)    
    return render_template('products/filter.html', product=product)

@product.app_template_filter('iva')
def iva_filter(product):
    
    if product['price']:
        return product['price'] * .20 + product['price']
    
    return 'No se ha podido calcular el precio + iva del producto. '

my_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Documento base </title>
</head>
<body>

    
    
    

    {% block body %}

        <h3> Estoy en base.html </h3>

    {% endblock %}

    Fin del documento base

</body>
</html>

my_app/templates/products/filter.html
<h3> {{product['name'] }}</h3>

<p> {{ product['category'] }}</p>

<p> Precio: {{ product['price'] | default('Precio no especificado', True) }}</p>


{% if product['price'] > 500 %}
    <p> Es demasiado caro, no me lo puedo permitir. </p>   
{% else %}
    <p> Está bien de precio. ¡Me lo quedo!  </p>   
{% endif %}

my_app/templates/products/index.html
<h3> Contenido index.html </h3>

{% extends "base.html" %}


{% block body %}

{% for key, product in products.items() %}
<div>
    <a href="{{ url_for('product.show', id=key) }}"> {{ product['name']}} </a>      
</div>
{% endfor %}


{% endblock %}

my_app/templates/products/show.html
<h3> {{product['name'] }}</h3>

<p> {{ product['category'] }}</p>

<p> {{ product['price'] }}</p>